[{"strategy": "retry", "code": "\npackage org.apache.commons.collections4;\n\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.*;\nimport java.util.Arrays;\nimport java.util.Iterator;\n\npublic class IteratorUtils_getTest {\n\n    @Test\n    public void testGetElementAtIndex() {\n        Iterator<Integer> iterator = Arrays.asList(1, 2, 3, 4, 5).iterator();\n        assertEquals(Integer.valueOf(3), IteratorUtils.get(iterator, 2));\n    }\n\n    @Test\n    public void testGetElementAtIndexOutOfBounds() {\n        Iterator<Integer> iterator = Arrays.asList(1, 2, 3).iterator();\n        assertThrows(IndexOutOfBoundsException.class, () -> IteratorUtils.get(iterator, 3));\n    }\n\n    @Test\n    public void testGetElementAtIndexEmptyIterator() {\n        Iterator<Integer> iterator = Arrays.asList().iterator();\n        assertThrows(IndexOutOfBoundsException.class, () -> IteratorUtils.get(iterator, 0));\n    }\n}\n"}]